### ISSUE TITLE
Tickets not opened in browser on Linux

### ISSUE THREAD

**Issue by japanoise** [lukeu/TracInstant#5]
1. Double click on ticket
2. Nothing happens; console shows this:

~~~
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
	at java.awt.Desktop.browse(Desktop.java:381)
	at net.bettyluke.util.DesktopUtils.browseTo(DesktopUtils.java:35)
	at net.bettyluke.tracinstant.ui.HtmlDescriptionPane.browseToTickets(HtmlDescriptionPane.java:100)
	at net.bettyluke.tracinstant.ui.TracInstantFrame.browseToSelectedTickets(TracInstantFrame.java:582)
	at net.bettyluke.tracinstant.ui.TracInstantFrame$4.mouseClicked(TracInstantFrame.java:475)
…
~~~

I have Firefox installed on my system and have set the `$BROWSER` environment variable.

**Comment by lukeu** [comment]
Hi, thanks for the report! Can you tell me more about your Linux system (version, window manager)?

Hmm, that's a tough one. The code (naturally) assumes that Java's `java.awt.Desktop` support will handle platform inconsistencies - but I know that class's support is patchy.

Googling around I see that
 - [netbeans encountered this ](https://netbeans.org/bugzilla/show_bug.cgi?id=255151) but they have their own module for HTML browser support, and I don't think I want to pull in that dependency.
 - Eclipse's 'oomph' [did too](https://bugs.eclipse.org/bugs/show_bug.cgi?id=468304). They went to lengths to just [execute a sequence of different commands](http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/commit/?id=a0d81f9e63351c030bf4922f57416fdd085cafe5), specific to each platform. Something like that may be the way to go, but quite a bit of extra code.

Also I don't have a copy of Linux around to test with. (I really should... I'm due for a hardware upgrade soon, and I may make my old one into a Linux box then.)

**Comment by japanoise** [comment]
I'm using KDE Plasma version 5.8.5 on Gentoo.

Not sure this is of much help - but if you can detect that I'm running Plasma, there's an option in system settings to set the default browser, which KDE apps honour when opening hyperlinks. So there must be some way of getting to it…

**Comment by lukeu** [comment]
Hi, I downloaded the Gentoo LiveDVD & selected Plasma. Unfortunately for me it freezes up after a few minutes of usage each time.

So I've created a patch, but I can't test it. Could you give it a go? You should be able to build & run using:

    git clone https://github.com/lukeu/TracInstant.git
    cd TracInstant
    git checkout issue-5
    ./gradlew run

**Comment by japanoise** [comment]
Brilliant, it works perfectly now. Thank you!

**Comment by lukeu** [comment]
> Brilliant, it works perfectly now. Thank you!
>
Great to hear! I'll merge that in to the master branch shortly then.

BTW here's a tip (since I haven't got much info on the wiki yet): you 
also can select multiple rows and press ENTER to view a selection of 
tickets in Trac itself.

**Comment by lukeu** [comment]
Pushed in 34da84a
